console.log("Africa")
console.log("Nigeria")
console.log("Egypt")
console.log("Kenya")
console.log("Asia")
for (let i = 0; i < 5; i++) {
console.log("China")
}
console.log("India")
console.log("Japan")
console.log("Europe")
console.log("Germany")
console.log("France")
console.log("Italy")
console.log("North America")
console.log("United States")
console.log("Canada")
console.log("Mexico")